cse112-sp24-group12/cse112-sp24-group12

source/server/main.js, source/server/package.json, source/server/util.js
=> added minimal backend

README.md
=> Add Code Climate badges to README

source/client/__tests__/unit/game.test.js, source/client/game.html, source/client/scripts/game.js, source/client/scripts/tarot.js
Code Climate was reporting a lot of issues with the length and complexity of the `init()` function in the original `game.js` implementation.
Refactored `init()` into appropriate functions, abstracted magic numbers, got rid of some unnecessarily slow code, and added appropriate JSDocs comments.
Also had to rewrite some of the unit test cases b/c the abstractions removed the need for the original functions being tested.
=> Code climate fixes

design/prototypes/text.txt
Makes progress on issue #1, need to finalize versus game design.
=> Added figma prototype, mutliplayer game design not finalized

source/client/scripts/versus/components/Card.js, source/client/scripts/versus/debug.js, source/client/scripts/versus/store.js, source/client/scripts/versus/util.js, source/client/scripts/versus/versus.js, source/client/styles/board.css, source/client/styles/versus.css, source/client/versus.html, source/server/util.js
=> Opponent cards slide into center screen (animation)

source/server/.eslintrc.json, source/server/__tests__/util.test.js, source/server/main.js, source/server/package.json, source/server/util.js
Closes #58 
(Changes to backend, so don't use preview link)
=> Added selection of game winner

source/client/scripts/versus/chat.js, source/client/scripts/versus/store.js, source/client/scripts/versus/versus.js, source/client/versus.html, source/server/logging.js, source/server/main.js
Added more logging statements, as well as more robust/styled/hierarchical log output through `logging.js` file.
=> More robust logging

source/client/scripts/stars.js, source/client/scripts/versus/components/Card.js, source/client/styles/board.css, source/client/styles/versus.css, source/client/versus.html
Reworked sliding animation and changed general board layout from flex to grid to allow more robust handling of each container.
=> Reworked sliding animation and page layout

source/server/main.js
=> Update instance information when a player leaves from lobby

source/client/scripts/versus/versus.js, source/client/styles/global.css, source/client/versus.html, source/server/main.js
=> Issue 70 single user start

source/client/scripts/versus/versus.js
=> Autofocus behavior when switching back to lobby screen

source/client/scripts/versus/store.js, source/client/scripts/versus/versus.js
=> Block multiple card selection

source/client/__tests__/e2e/game.test.js, source/client/scripts/game.js, source/client/styles/game.css
=> Prevent early click

source/client/scripts/versus/versus.js, source/client/styles/global.css, source/client/styles/versus.css, source/client/versus.html
=> Round winner animation

source/server/__tests__/util.test.js, source/server/main.js, source/server/util.js
Added more unit testing to backend for functions that can be easily encapsulated
Closes #72
=> Backend unit testing

source/client/scripts/versus/versus.js, source/client/styles/global.css, source/client/styles/versus.css, source/client/versus.html
Adds functionality to rulebook button.
Requires copy for descriptions of the actual world events (right now they are just placeholders); @harshilxd can add that in
=> Created basic rules popup

source/client/__tests__/e2e/game.test.js, source/client/game.html, source/client/scripts/game.js, source/client/styles/game.css
=> Wizard animation on solo mode game end

source/client/scripts/versus/versus.js, source/client/styles/versus.css, source/server/main.js
Fixed behavior of game with multiple open tabs (previously, game would implode)
Fixed behavior of vertical round-end text w.r.t. horizontal size of window (what @arjunghoshal mentioned in class)
Changed length of game-end deletion timeout from 5 seconds -> 20 seconds
=> Multi-tab Fix + two small additions

source/client/styles/game.css, source/client/styles/global.css, source/client/styles/results.css
=> Change styling for solo mode

source/client/scripts/versus/versus.js, source/client/styles/board.css, source/client/styles/versus.css
closes #47 
[video of animation](https://www.awesomescreenshot.com/video/28444957?key=30e5666478a5f7a6bb5bcc4f838a61f2)
=> animate cards being dealt on versus mode

source/client/versus.html
=> Change for video

source/client/styles/board.css
=> Video change
